services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  react-app:
    image: ghcr.io/pedro-gbf/pedrofernand.es:latest
    restart: unless-stopped
    expose:
      - "3000" # Changed from 80 to 3000

volumes:
  caddy_data:
  caddy_config:
